library(dplyr)
library(ggplot2)
cyber.security.question.response_1=bind_rows(cyber.security.1_question.response,cyber.security.2_question.response,cyber.security.3_question.response,cyber.security.4_question.response ,cyber.security.5_question.response,cyber.security.6_question.response,cyber.security.7_question.response)
#Count the number of answers to each question
(t=table(cyber.security.question.response_1$quiz_question))
t=as.data.frame(t)
colnames(t) = c("quiz_question", "answers_numbers")
#Counting the number of people who answered the questions
quiz_question_1.7.1= cyber.security.question.response_1 %>% filter(quiz_question == "1.7.1") 
quiz_question_1.7.2= cyber.security.question.response_1 %>% filter(quiz_question == "1.7.2") 
quiz_question_1.7.3= cyber.security.question.response_1 %>% filter(quiz_question == "1.7.3")
quiz_question_1.7.4= cyber.security.question.response_1 %>% filter(quiz_question == "1.7.4")
quiz_question_1.7.5= cyber.security.question.response_1 %>% filter(quiz_question == "1.7.5")
quiz_question_1.7.6= cyber.security.question.response_1 %>% filter(quiz_question == "1.7.6")
quiz_question_1.8.1= cyber.security.question.response_1 %>% filter(quiz_question == "1.8.1") 
quiz_question_1.8.2= cyber.security.question.response_1 %>% filter(quiz_question == "1.8.2") 
quiz_question_1.8.3= cyber.security.question.response_1 %>% filter(quiz_question == "1.8.3")
quiz_question_1.8.4= cyber.security.question.response_1 %>% filter(quiz_question == "1.8.4")
quiz_question_1.8.5= cyber.security.question.response_1 %>% filter(quiz_question == "1.8.5")
quiz_question_1.8.6= cyber.security.question.response_1 %>% filter(quiz_question == "1.8.6")
quiz_question_2.19.1= cyber.security.question.response_1 %>% filter(quiz_question == "2.19.1")
quiz_question_2.20.1= cyber.security.question.response_1 %>% filter(quiz_question == "2.20.1")
quiz_question_2.8.1= cyber.security.question.response_1 %>% filter(quiz_question == "2.8.1") 
quiz_question_2.8.2= cyber.security.question.response_1 %>% filter(quiz_question == "2.8.2") 
quiz_question_2.8.3= cyber.security.question.response_1 %>% filter(quiz_question == "2.8.3")
quiz_question_3.11.1= cyber.security.question.response_1 %>% filter(quiz_question == "3.11.1") 
quiz_question_3.11.2= cyber.security.question.response_1 %>% filter(quiz_question == "3.11.2") 
quiz_question_3.11.3= cyber.security.question.response_1 %>% filter(quiz_question == "3.11.3")
quiz_question_3.18.1= cyber.security.question.response_1 %>% filter(quiz_question == "3.18.1")
quiz_question_3.18.2= cyber.security.question.response_1 %>% filter(quiz_question == "3.18.2")
quiz_question_3.18.3= cyber.security.question.response_1 %>% filter(quiz_question == "3.18.3")
quiz_question_3.18.4= cyber.security.question.response_1 %>% filter(quiz_question == "3.18.4")
quiz_question_3.18.5= cyber.security.question.response_1 %>% filter(quiz_question == "3.18.5")
quiz_question_3.18.6= cyber.security.question.response_1 %>% filter(quiz_question == "3.18.6")
quiz_question_3.18.7= cyber.security.question.response_1 %>% filter(quiz_question == "3.18.7")
quiz_question_3.18.8= cyber.security.question.response_1 %>% filter(quiz_question == "3.18.8")
quiz_question_3.18.9= cyber.security.question.response_1 %>% filter(quiz_question == "3.18.9")
No.people_1.7.1=length(unique(quiz_question_1.7.1$learner_id))
No.people_1.7.2=length(unique(quiz_question_1.7.2$learner_id))
No.people_1.7.3=length(unique(quiz_question_1.7.3$learner_id))
No.people_1.7.4=length(unique(quiz_question_1.7.4$learner_id))
No.people_1.7.5=length(unique(quiz_question_1.7.5$learner_id))
No.people_1.7.6=length(unique(quiz_question_1.7.6$learner_id))
No.people_1.8.1=length(unique(quiz_question_1.8.1$learner_id))
No.people_1.8.2=length(unique(quiz_question_1.8.2$learner_id))
No.people_1.8.3=length(unique(quiz_question_1.8.3$learner_id))
No.people_1.8.4=length(unique(quiz_question_1.8.4$learner_id))
No.people_1.8.5=length(unique(quiz_question_1.8.5$learner_id))
No.people_1.8.6=length(unique(quiz_question_1.8.6$learner_id))
No.people_2.19.1=length(unique(quiz_question_2.19.1$learner_id))
No.people_2.20.1=length(unique(quiz_question_2.20.1$learner_id))
No.people_2.8.1=length(unique(quiz_question_2.8.1$learner_id))
No.people_2.8.2=length(unique(quiz_question_2.8.2$learner_id))
No.people_2.8.3=length(unique(quiz_question_2.8.3$learner_id))
No.people_3.11.1=length(unique(quiz_question_3.11.1$learner_id))
No.people_3.11.2=length(unique(quiz_question_3.11.2$learner_id))
No.people_3.11.3=length(unique(quiz_question_3.11.3$learner_id))
No.people_3.18.1=length(unique(quiz_question_3.18.1$learner_id))
No.people_3.18.2=length(unique(quiz_question_3.18.2$learner_id))
No.people_3.18.3=length(unique(quiz_question_3.18.3$learner_id))
No.people_3.18.4=length(unique(quiz_question_3.18.4$learner_id))
No.people_3.18.5=length(unique(quiz_question_3.18.5$learner_id))
No.people_3.18.6=length(unique(quiz_question_3.18.6$learner_id))
No.people_3.18.7=length(unique(quiz_question_3.18.7$learner_id))
No.people_3.18.8=length(unique(quiz_question_3.18.8$learner_id))
No.people_3.18.9=length(unique(quiz_question_3.18.9$learner_id))
t_1=data.frame(question=c(t$quiz_question),No.people=c(No.people_1.7.1,No.people_1.7.2,No.people_1.7.3,No.people_1.7.4,No.people_1.7.5,No.people_1.7.6,No.people_1.8.1,No.people_1.8.2,No.people_1.8.3,No.people_1.8.4,No.people_1.8.5,No.people_1.8.6,No.people_2.19.1,No.people_2.20.1,No.people_2.8.1,No.people_2.8.2,No.people_2.8.3,No.people_3.11.1,No.people_3.11.2,No.people_3.11.3,No.people_3.18.1,No.people_3.18.2,No.people_3.18.3,No.people_3.18.4,No.people_3.18.5,No.people_3.18.6,No.people_3.18.7,No.people_3.18.8,No.people_3.18.9))
t_1
#Number of repeated answers
rep=data.frame(question_1=c(t$quiz_question), repeated_answers=c(t$answers_numbers-t_1$No.people))
rep
#Drawings
ggplot(t, aes(x=quiz_question,y=answers_numbers,fill=answers_numbers))+geom_bar(stat="identity")+coord_polar(theta = "x", direction=1)
picture=ggplot(t_1, aes(x=question,y=No.people,fill=No.people))+geom_bar(stat="identity")+coord_polar(theta = "x", direction=1)
picture+scale_fill_gradient(low='white',high='red')+ 
  theme_bw()
pictire_1=ggplot(rep, aes(x=question_1,y=repeated_answers,fill=repeated_answers))+geom_bar(stat="identity")+coord_polar(theta = "x", direction=1)
pictire_1 +scale_fill_gradient(low='pink',high='green')+ 
  theme_bw()

